# Generated by Django 4.1 on 2022-12-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=155)),
                ('customer_number', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_address', models.TextField(max_length=200)),
                ('customer_dob', models.DateField()),
                ('info_added_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
