# Generated by Django 4.1 on 2022-12-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(choices=[('1', 'Birthday'), ('2', 'Marriage'), ('3', 'Anniversary')], default='1', max_length=155)),
                ('event_date', models.DateField()),
                ('info_added_on', models.DateField(auto_now=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
    ]
