# Generated by Django 4.1 on 2022-12-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_time_type',
            field=models.CharField(choices=[('1', 'Single Time Event'), ('2', 'Recurring Event')], default='1', max_length=155),
        ),
    ]
