# Generated by Django 4.1 on 2022-12-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event_event_time_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Marriage', 'Marriage'), ('3', 'Anniversary')], default='1', max_length=155),
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(to='home.tag'),
        ),
    ]
