# Generated by Django 4.1 on 2022-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag_alter_customer_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_time_type',
            field=models.CharField(choices=[('Single Time Event', 'Single Time Event'), ('Recurring Event', 'Recurring Event')], max_length=155),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Marriage', 'Marriage'), ('Anniversary', 'Anniversary')], default='1', max_length=155),
        ),
    ]
